name: dart_auth_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.11.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
