name: Backend CI & Dispatch Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            your-mukeshsaini7/flutter-backend:latest
            your-mukeshsaini7/flutter-backend:${{ github.sha }}

  trigger-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: mukeshsaini143/deploy-repo
          event-type: deploy
